### ISSUE TITLE
Install.sh fails on "no internet connection detected" if system time is wrong

### ISSUE THREAD

**Issue by rogusdev** [ChimeraOS/install-media#62]
GitHub seems have refreshed its SSL cert on mar 7, but my system thinks it's Feb 11 for some reason (Ace magic amr5), which leads the install.sh curl check against GitHub to fail, even tho there is in fact an Internet connection.

The easiest possible solution is to simply add -k (allow insecure) when simply checking if GitHub is reachable:
https://github.com/ChimeraOS/install-media/blob/e820ed27c053f521e86ebfd971c3165f6f4b862b/chimeraos/airootfs/root/install.sh#L40

However that fails the installation later (I assume some other curl calls to GitHub which fail security). So basically I'm hoping we can somehow alert the user that their bios clock is off, or to correct the date as part of the installer or something.

This caused me a lot of confusion when trying to setup for a good while until I started futzing on my own -- I knew the Internet was there and it took a bit to figure out why chimeraos thought it was not there.

**Comment by gillham** [comment]
I just ran into this exact same issue. The installer kept telling me to configure the wired Ethernet interface because it couldn't get to the internet. 

In fact it was a certificate error due to the clock being wrong and the certificate was not yet valid. The test machine I am installing on seems to have a dead cmos battery, but the time is easily gotten from the internet. 

I would recommend setting the system clock via NTP prior to attempting any certificate based activity during the installation.

While a person should be making sure their pc clock is correct it is an easy failure mode to avoid.

**Comment by alkazar** [comment]
Thank you for the report. This issue is now resolved in the latest ISO (2024-04-01).
